#!/usr/bin/env bash
# Rebuild global Caddyfile from clients/*/.env and reload Caddy.
#
# Usage:
#   WEBINO_ROOT=/opt/webino ./render-proxy.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEBINO_ROOT="${WEBINO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"

CLIENTS_DIR="${WEBINO_ROOT}/clients"
PROXY_DIR="${WEBINO_ROOT}/proxy"
FRAGMENT="${PROXY_DIR}/Caddyfile.fragment"
OUT="${PROXY_DIR}/Caddyfile"
TMP="$(mktemp)"

log() { printf '[webino-proxy] %s\n' "$*" >&2; }
die() { printf '[webino-proxy] ERROR: %s\n' "$*" >&2; exit 1; }

[[ -d "$PROXY_DIR" ]] || die "proxy dir missing: ${PROXY_DIR}"
[[ -f "$FRAGMENT" ]] || die "fragment missing: ${FRAGMENT}"

cleanup() { rm -f "$TMP"; }
trap cleanup EXIT

{
  cat <<'EOF'
# Generated by render-proxy.sh — do not edit by hand.

{
	servers {
		protocols h1 h2 h3
	}
}

EOF

  count=0
  if [[ -d "$CLIENTS_DIR" ]]; then
    shopt -s nullglob
    for envfile in "${CLIENTS_DIR}"/*/.env; do
      slug=""
      domain=""
      # shellcheck disable=SC1090
      while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// }" ]] && continue
        case "$line" in
          CLIENT_SLUG=*) slug="${line#CLIENT_SLUG=}" ;;
          CLIENT_DOMAIN=*) domain="${line#CLIENT_DOMAIN=}" ;;
        esac
      done < "$envfile"

      slug="${slug//\"/}"
      domain="${domain//\"/}"
      slug="${slug//\'/}"
      domain="${domain//\'/}"

      if [[ -z "$slug" || -z "$domain" ]]; then
        log "skip $(dirname "$envfile"): missing CLIENT_SLUG or CLIENT_DOMAIN"
        continue
      fi

      sed \
        -e "s/{\$CLIENT_DOMAIN}/${domain}/g" \
        -e "s/{\$CLIENT_SLUG}/${slug}/g" \
        "$FRAGMENT"
      echo
      count=$((count + 1))
      log "site ${domain} → ${slug}-frontend / ${slug}-backend"
    done
    shopt -u nullglob
  fi

  if [[ "$count" -eq 0 ]]; then
    cat <<'EOF'
:80 {
	respond "Webino edge proxy — no clients configured yet." 200
}
EOF
  fi
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT

log "wrote ${OUT} (${count:-0} client site(s))"

# Reload running Caddy if present
if docker compose -f "${PROXY_DIR}/docker-compose.yml" ps --status running 2>/dev/null | grep -q caddy; then
  if docker compose -f "${PROXY_DIR}/docker-compose.yml" exec -T caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null; then
    log "caddy reloaded"
  else
    log "reload failed — restarting proxy stack"
    (cd "$PROXY_DIR" && docker compose up -d)
  fi
else
  log "caddy not running — start with: cd ${PROXY_DIR} && docker compose up -d"
fi
