import type { ModuleManifest } from "@/kernel/types"

export const marketingManifest: ModuleManifest = {
  slug: "marketing",
  nameFa: "بازاریابی",
  nameEn: "Marketing",
  siteTypes: ["ecommerce", "magazine", "cafe", "corporate"],
  submodules: ["coupons", "bot-broadcast", "bot-campaigns", "sms", "newsletter"],
  adminNav: { section: "marketing", order: 40 },
  adminRoutes: [
    { path: "marketing/coupons", submodule: "coupons", page: "coupons", labelKey: "nav.coupons", section: "marketing", order: 40 },
    { path: "marketing/coupons/new", submodule: "coupons", page: "coupon-editor", labelKey: "nav.coupons", section: "marketing", order: 40 },
    { path: "marketing/coupons/:couponId", submodule: "coupons", page: "coupon-editor", labelKey: "nav.coupons", section: "marketing", order: 40 },
    { path: "marketing/bot-broadcast", submodule: "bot-broadcast", page: "bot-broadcast", labelKey: "nav.bot_broadcast", section: "marketing", order: 41 },
    { path: "marketing/bot-campaigns", submodule: "bot-campaigns", page: "bot-campaigns", labelKey: "nav.bot_campaigns", section: "marketing", order: 42 },
    { path: "marketing/sms", submodule: "sms", page: "sms-home", labelKey: "nav.sms_panel", section: "marketing", order: 43 },
    { path: "marketing/sms/send", submodule: "sms", page: "sms-send", labelKey: "nav.sms_send", section: "marketing", order: 44 },
    { path: "marketing/sms/reports", submodule: "sms", page: "sms-reports", labelKey: "nav.sms_reports", section: "marketing", order: 45 },
    { path: "marketing/sms/targeted", submodule: "sms", page: "sms-targeted", labelKey: "nav.sms_targeted", section: "marketing", order: 46 },
    { path: "marketing/sms/inbox", submodule: "sms", page: "sms-inbox", labelKey: "nav.sms_inbox", section: "marketing", order: 47 },
    { path: "marketing/sms/drafts", submodule: "sms", page: "sms-drafts", labelKey: "nav.sms_drafts", section: "marketing", order: 48 },
    { path: "marketing/sms/phonebook", submodule: "sms", page: "sms-phonebook", labelKey: "nav.sms_phonebook", section: "marketing", order: 49 },
    { path: "marketing/sms/scheduled", submodule: "sms", page: "sms-scheduled", labelKey: "nav.sms_scheduled", section: "marketing", order: 50 },
    { path: "marketing/sms/patterns", submodule: "sms", page: "sms-patterns", labelKey: "nav.sms_patterns", section: "marketing", order: 51 },
    { path: "marketing/sms/secretaries", submodule: "sms", page: "sms-secretaries", labelKey: "nav.sms_secretaries", section: "marketing", order: 52 },
    { path: "marketing/sms/wallet", submodule: "sms", page: "sms-wallet", labelKey: "nav.sms_wallet", section: "marketing", order: 53 },
    { path: "marketing/sms/lines", submodule: "sms", page: "sms-lines", labelKey: "nav.sms_lines", section: "marketing", order: 54 },
    { path: "marketing/sms/newsletter", submodule: "sms", page: "sms-newsletter", labelKey: "nav.sms_newsletter", section: "marketing", order: 55 },
    { path: "marketing/sms/topup", submodule: "sms", page: "sms-topup", labelKey: "nav.sms_topup", section: "marketing", order: 56 },
    { path: "marketing/sms/payment-callback", submodule: "sms", page: "sms-payment-callback", labelKey: "nav.sms_topup", section: "marketing", order: 57 },
  ],
  siteRoutes: [],
}
