import type { ModuleManifest } from "@/kernel/types"

export const magazineManifest: ModuleManifest = {
  slug: "magazine",
  nameFa: "مجله",
  nameEn: "Magazine",
  siteTypes: ["magazine", "ecommerce", "corporate"],
  submodules: ["issues", "articles", "series", "authors"],
  adminNav: { section: "content", order: 16 },
  adminRoutes: [
    {
      path: "magazine",
      submodule: "articles",
      page: "articles",
      labelKey: "nav.magazine_posts",
      section: "content",
      order: 16,
      navGroup: "magazine",
      navOrder: 0,
      capability: "content.manage",
    },
    {
      path: "magazine/posts",
      submodule: "articles",
      page: "articles",
      labelKey: "nav.magazine_posts",
      section: "content",
      order: 16,
      navGroup: "magazine",
      navOrder: 0,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "magazine/new",
      submodule: "articles",
      page: "post-editor",
      labelKey: "nav.magazine_posts",
      section: "content",
      order: 16,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "magazine/posts/:postId",
      submodule: "articles",
      page: "post-editor",
      labelKey: "nav.magazine_posts",
      section: "content",
      order: 16,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "magazine/categories",
      submodule: "articles",
      page: "categories",
      labelKey: "nav.magazine_categories",
      section: "content",
      order: 16,
      navGroup: "magazine",
      navOrder: 1,
      capability: "content.manage",
    },
  ],
  siteRoutes: [
    { path: "magazine", submodule: "articles", labelKey: "site.magazine" },
    { path: "magazine/:slug", submodule: "articles", labelKey: "site.magazine_article" },
  ],
}
