import type { ModuleManifest } from "@/kernel/types"

export const commerceManifest: ModuleManifest = {
  slug: "commerce",
  nameFa: "فروش",
  nameEn: "Commerce",
  siteTypes: ["ecommerce", "cafe"],
  submodules: [
    "catalog",
    "brands",
    "attributes",
    "variants",
    "pricing",
    "marketplace",
    "cart",
    "checkout",
    "orders",
    "c2c",
    "wallet",
    "pos",
    "inventory",
  ],
  adminNav: { section: "commerce", order: 20 },
  publicRoutes: ["/shop", "/catalogue"],
  adminRoutes: [
    { path: "products", submodule: "catalog", page: "products", labelKey: "nav.products", section: "commerce", order: 20 },
    { path: "products/new", submodule: "catalog", page: "product-editor", labelKey: "nav.products", section: "commerce", order: 20 },
    { path: "products/:productId", submodule: "catalog", page: "product-editor", labelKey: "nav.products", section: "commerce", order: 20 },
    { path: "brands", submodule: "brands", page: "brands", labelKey: "nav.brands", section: "commerce", order: 21 },
    { path: "brands/new", submodule: "brands", page: "brand-editor", labelKey: "nav.brands", section: "commerce", order: 21 },
    { path: "brands/:brandId", submodule: "brands", page: "brand-editor", labelKey: "nav.brands", section: "commerce", order: 21 },
    { path: "product-categories", submodule: "catalog", page: "product-categories", labelKey: "nav.product_categories", section: "commerce", order: 22 },
    { path: "product-categories/new", submodule: "catalog", page: "product-category-editor", labelKey: "nav.product_categories", section: "commerce", order: 22 },
    { path: "product-categories/:categoryId", submodule: "catalog", page: "product-category-editor", labelKey: "nav.product_categories", section: "commerce", order: 22 },
    { path: "attributes", submodule: "attributes", page: "attributes", labelKey: "nav.attributes", section: "commerce", order: 23 },
    { path: "attributes/new", submodule: "attributes", page: "attribute-editor", labelKey: "nav.attributes", section: "commerce", order: 23 },
    { path: "attributes/:attributeId", submodule: "attributes", page: "attribute-editor", labelKey: "nav.attributes", section: "commerce", order: 23 },
    { path: "pricing/quick-add", submodule: "pricing", page: "pricing-quick-add", labelKey: "nav.pricing_quick_add", section: "commerce", order: 24 },
    { path: "pricing/bulk-editor", submodule: "pricing", page: "pricing-bulk-editor", labelKey: "nav.pricing_bulk_editor", section: "commerce", order: 25 },
    { path: "pricing/price-changer", submodule: "pricing", page: "pricing-price-changer", labelKey: "nav.pricing_price_changer", section: "commerce", order: 26 },
    { path: "orders", submodule: "orders", page: "orders", labelKey: "nav.orders", section: "commerce", order: 40 },
    { path: "orders/new", submodule: "orders", page: "order-composer", labelKey: "nav.order_new", section: "commerce", order: 41 },
    { path: "orders/c2c-receipts", submodule: "c2c", page: "c2c-receipts", labelKey: "nav.c2c_receipts", section: "commerce", order: 42 },
    { path: "orders/wallet-withdrawals", submodule: "wallet", page: "wallet-withdrawals", labelKey: "nav.wallet_withdrawals", section: "commerce", order: 43 },
    { path: "orders/:orderId/edit", submodule: "orders", page: "order-composer", labelKey: "nav.order_new", section: "commerce", order: 41 },
    { path: "orders/:orderId", submodule: "orders", page: "order-detail", labelKey: "nav.orders", section: "commerce", order: 40 },
    { path: "settings/c2c", submodule: "c2c", page: "c2c-settings", labelKey: "nav.c2c_settings", section: "commerce", order: 44 },
    { path: "settings/wallet", submodule: "wallet", page: "wallet-settings", labelKey: "nav.wallet_settings", section: "commerce", order: 45 },
    { path: "pos", submodule: "pos", page: "pos", labelKey: "nav.pos", section: "pos", order: 50 },
    { path: "pos/pay-link", submodule: "pos", page: "pos-pay-link", labelKey: "nav.pos_pay_link", section: "pos", order: 51 },
    { path: "pos/my-orders", submodule: "pos", page: "orders", labelKey: "nav.pos_my_orders", section: "pos", order: 52 },
    { path: "cart", submodule: "cart", labelKey: "nav.cart", section: "commerce", order: 30 },
    { path: "checkout", submodule: "checkout", labelKey: "nav.checkout", section: "commerce", order: 31 },
    { path: "inventory", submodule: "inventory", labelKey: "nav.inventory", section: "commerce", order: 33 },
    { path: "catalog", submodule: "catalog", page: "products", labelKey: "nav.products", section: "commerce", order: 19 },
  ],
  siteRoutes: [
    { path: "shop", submodule: "catalog", labelKey: "site.shop" },
    { path: "catalogue", submodule: "catalog", labelKey: "site.catalogue" },
  ],
}
