import type { ModuleManifest } from "@/kernel/types"

export const commerceManifest: ModuleManifest = {
  slug: "commerce",
  nameFa: "فروش",
  nameEn: "Commerce",
  siteTypes: ["ecommerce", "cafe"],
  submodules: [
    "catalog",
    "brands",
    "attributes",
    "variants",
    "pricing",
    "marketplace",
    "cart",
    "checkout",
    "orders",
    "c2c",
    "wallet",
    "pos",
    "inventory",
    "accounting",
    "account",
  ],
  adminNav: { section: "commerce", order: 20 },
  publicRoutes: ["/shop", "/catalogue"],
  adminRoutes: [
    {
      path: "products",
      submodule: "catalog",
      page: "products",
      labelKey: "nav.products",
      section: "commerce",
      order: 20,
      navGroup: "shop",
      navOrder: 0,
    },
    {
      path: "products/new",
      submodule: "catalog",
      page: "product-editor",
      labelKey: "nav.products",
      section: "commerce",
      order: 20,
      navHidden: true,
    },
    {
      path: "products/:productId",
      submodule: "catalog",
      page: "product-editor",
      labelKey: "nav.products",
      section: "commerce",
      order: 20,
      navHidden: true,
    },
    {
      path: "brands",
      submodule: "brands",
      page: "brands",
      labelKey: "nav.brands",
      section: "commerce",
      order: 20,
      navGroup: "shop",
      navOrder: 1,
    },
    {
      path: "brands/new",
      submodule: "brands",
      page: "brand-editor",
      labelKey: "nav.brands",
      section: "commerce",
      order: 20,
      navHidden: true,
    },
    {
      path: "brands/:brandId",
      submodule: "brands",
      page: "brand-editor",
      labelKey: "nav.brands",
      section: "commerce",
      order: 20,
      navHidden: true,
    },
    {
      path: "product-categories",
      submodule: "catalog",
      page: "product-categories",
      labelKey: "nav.product_categories",
      section: "commerce",
      order: 20,
      navGroup: "shop",
      navOrder: 2,
    },
    {
      path: "product-categories/new",
      submodule: "catalog",
      page: "product-category-editor",
      labelKey: "nav.product_categories",
      section: "commerce",
      order: 20,
      navHidden: true,
    },
    {
      path: "product-categories/:categoryId",
      submodule: "catalog",
      page: "product-category-editor",
      labelKey: "nav.product_categories",
      section: "commerce",
      order: 20,
      navHidden: true,
    },
    {
      path: "attributes",
      submodule: "attributes",
      page: "attributes",
      labelKey: "nav.attributes",
      section: "commerce",
      order: 20,
      navGroup: "shop",
      navOrder: 3,
    },
    {
      path: "attributes/new",
      submodule: "attributes",
      page: "attribute-editor",
      labelKey: "nav.attributes",
      section: "commerce",
      order: 20,
      navHidden: true,
    },
    {
      path: "attributes/:attributeId",
      submodule: "attributes",
      page: "attribute-editor",
      labelKey: "nav.attributes",
      section: "commerce",
      order: 20,
      navHidden: true,
    },
    {
      path: "product-catalog",
      submodule: "catalog",
      page: "product-catalog",
      labelKey: "nav.product_catalog",
      section: "commerce",
      order: 20,
      navGroup: "shop",
      navOrder: 4,
    },
    {
      path: "pricing/quick-add",
      submodule: "pricing",
      page: "pricing-quick-add",
      labelKey: "nav.pricing_quick_add",
      section: "commerce",
      order: 20,
      navGroup: "shop",
      navOrder: 5,
    },
    {
      path: "pricing/bulk-editor",
      submodule: "pricing",
      page: "pricing-bulk-editor",
      labelKey: "nav.pricing_bulk_editor",
      section: "commerce",
      order: 20,
      navGroup: "shop",
      navOrder: 6,
    },
    {
      path: "pricing/price-changer",
      submodule: "pricing",
      page: "pricing-price-changer",
      labelKey: "nav.pricing_price_changer",
      section: "commerce",
      order: 20,
      navGroup: "shop",
      navOrder: 7,
    },
    {
      path: "orders",
      submodule: "orders",
      page: "orders",
      labelKey: "nav.orders",
      section: "commerce",
      order: 21,
      navGroup: "orders",
      navOrder: 0,
    },
    {
      path: "orders/new",
      submodule: "orders",
      page: "order-composer",
      labelKey: "nav.order_new",
      section: "commerce",
      order: 21,
      navGroup: "orders",
      navOrder: 1,
    },
    {
      path: "orders/c2c-receipts",
      submodule: "c2c",
      page: "c2c-receipts",
      labelKey: "nav.c2c_receipts",
      section: "commerce",
      order: 21,
      navGroup: "orders",
      navOrder: 2,
    },
    {
      path: "orders/wallet-withdrawals",
      submodule: "wallet",
      page: "wallet-withdrawals",
      labelKey: "nav.wallet_withdrawals",
      section: "commerce",
      order: 21,
      navGroup: "orders",
      navOrder: 3,
    },
    {
      path: "orders/:orderId/edit",
      submodule: "orders",
      page: "order-composer",
      labelKey: "nav.order_new",
      section: "commerce",
      order: 21,
      navHidden: true,
    },
    {
      path: "orders/:orderId",
      submodule: "orders",
      page: "order-detail",
      labelKey: "nav.orders",
      section: "commerce",
      order: 21,
      navHidden: true,
    },
    {
      path: "settings/c2c",
      submodule: "c2c",
      page: "c2c-settings",
      labelKey: "nav.c2c_settings",
      section: "commerce",
      order: 21,
      navHidden: true,
    },
    {
      path: "settings/wallet",
      submodule: "wallet",
      page: "wallet-settings",
      labelKey: "nav.wallet_settings",
      section: "commerce",
      order: 21,
      navHidden: true,
    },
    {
      path: "pos",
      submodule: "pos",
      page: "pos",
      labelKey: "nav.pos",
      section: "commerce",
      order: 22,
      navGroup: "pos",
      navOrder: 0,
    },
    {
      path: "pos/pay-link",
      submodule: "pos",
      page: "pos-pay-link",
      labelKey: "nav.pos_pay_link",
      section: "commerce",
      order: 22,
      navGroup: "pos",
      navOrder: 1,
    },
    {
      path: "pos/my-orders",
      submodule: "pos",
      page: "orders",
      labelKey: "nav.pos_my_orders",
      section: "commerce",
      order: 22,
      navGroup: "pos",
      navOrder: 2,
    },
    {
      path: "account",
      submodule: "account",
      page: "account-home",
      labelKey: "nav.account_home",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 0,
    },
    {
      path: "account/orders",
      submodule: "account",
      page: "account-orders",
      labelKey: "nav.account_orders",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 1,
    },
    {
      path: "account/orders/:orderId",
      submodule: "account",
      page: "account-order-detail",
      labelKey: "nav.account_orders",
      section: "commerce",
      order: 24,
      navHidden: true,
    },
    {
      path: "account/addresses",
      submodule: "account",
      page: "account-addresses",
      labelKey: "nav.account_addresses",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 2,
    },
    {
      path: "account/notifications",
      submodule: "account",
      page: "account-notifications",
      labelKey: "nav.account_notifications",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 3,
    },
    {
      path: "account/favorites",
      submodule: "account",
      page: "account-favorites",
      labelKey: "nav.account_favorites",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 4,
    },
    {
      path: "account/reviews",
      submodule: "account",
      page: "account-reviews",
      labelKey: "nav.account_reviews",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 5,
    },
    {
      path: "account/profile",
      submodule: "account",
      page: "account-profile",
      labelKey: "nav.account_profile",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 6,
    },
    {
      path: "account/wallet",
      submodule: "account",
      page: "account-wallet",
      labelKey: "nav.account_wallet",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 7,
    },
    {
      path: "account/tickets",
      submodule: "account",
      page: "account-tickets",
      labelKey: "nav.account_tickets",
      section: "commerce",
      order: 24,
      navGroup: "account",
      navOrder: 8,
    },
    {
      path: "accounting",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_overview",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 0,
    },
    {
      path: "accounting/overview",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_overview",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 0,
      navHidden: true,
    },
    {
      path: "accounting/tax",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_tax",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 1,
    },
    {
      path: "accounting/tax-setup",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_tax_setup",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 2,
    },
    {
      path: "accounting/chart",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_chart",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 3,
    },
    {
      path: "accounting/journals",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_journals",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 4,
    },
    {
      path: "accounting/persons",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_persons",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 5,
    },
    {
      path: "accounting/products",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_products",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 6,
    },
    {
      path: "accounting/invoices",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_invoices",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 7,
    },
    {
      path: "accounting/purchases",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_purchases",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 8,
    },
    {
      path: "accounting/expenses",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_expenses",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 9,
    },
    {
      path: "accounting/treasury",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_treasury",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 10,
    },
    {
      path: "accounting/checks",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_checks",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 11,
    },
    {
      path: "accounting/installments",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_installments",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 12,
    },
    {
      path: "accounting/warehouses",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_warehouses",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 13,
    },
    {
      path: "accounting/production",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_production",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 14,
    },
    {
      path: "accounting/moadian",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_moadian",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 15,
    },
    {
      path: "accounting/hesabfa",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_hesabfa",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 16,
    },
    {
      path: "accounting/payroll",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_payroll",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 17,
    },
    {
      path: "accounting/my-payroll",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_my_payroll",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 18,
    },
    {
      path: "accounting/projects",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_projects",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 19,
    },
    {
      path: "accounting/reports",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_reports",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 20,
    },
    {
      path: "accounting/tools",
      submodule: "accounting",
      page: "accounting",
      labelKey: "nav.accounting_tools",
      section: "commerce",
      order: 23,
      navGroup: "accounting",
      navOrder: 21,
    },
    {
      path: "cart",
      submodule: "cart",
      labelKey: "nav.cart",
      section: "commerce",
      order: 30,
      navHidden: true,
    },
    {
      path: "checkout",
      submodule: "checkout",
      labelKey: "nav.checkout",
      section: "commerce",
      order: 31,
      navHidden: true,
    },
    {
      path: "inventory",
      submodule: "inventory",
      labelKey: "nav.inventory",
      section: "commerce",
      order: 33,
      navHidden: true,
    },
    {
      path: "catalog",
      submodule: "catalog",
      page: "products",
      labelKey: "nav.products",
      section: "commerce",
      order: 19,
      navHidden: true,
    },
  ],
  siteRoutes: [
    { path: "shop", submodule: "catalog", labelKey: "site.shop" },
    { path: "catalogue", submodule: "catalog", labelKey: "site.catalogue" },
  ],
}
