import type { ModuleManifest } from "@/kernel/types"

const coreRoutes = (sub: string, labelKey: string, section = "core", order = 0) => ({
  path: sub === "dashboard" ? "" : sub,
  submodule: sub,
  labelKey,
  section,
  order,
})

export const coreManifest: ModuleManifest = {
  slug: "core",
  nameFa: "هسته",
  nameEn: "Core",
  siteTypes: ["ecommerce", "magazine", "cafe", "resume", "corporate"],
  submodules: ["auth", "setup", "tenant", "dashboard", "settings", "media", "i18n", "modules", "themes"],
  adminNav: { section: "core", order: 0 },
  adminRoutes: [
    coreRoutes("dashboard", "nav.dashboard", "overview", 0),
    {
      path: "themes",
      submodule: "themes",
      labelKey: "nav.themes",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/marketplace",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.marketplace",
      section: "admin",
      order: 90,
    },
    {
      path: "settings",
      submodule: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/reviews",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.users_comments",
      section: "users",
      order: 50,
      navGroup: "users",
      navOrder: 3,
      capability: "reviews.moderate",
      menuKey: "settings/shop/reviews",
    },
    {
      path: "settings/site/:section",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/:section",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/:section/:sub",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/:section/:sub/:page",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/ext/:moduleSlug",
      submodule: "settings",
      page: "settings-ext",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/site/security",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings_site",
      section: "admin",
      order: 91,
      navGroup: "settings",
      navOrder: 0,
      capability: "settings.manage",
      menuKey: "settings",
    },
    {
      path: "settings/shop/general",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings_shop",
      section: "admin",
      order: 91,
      navGroup: "settings",
      navOrder: 1,
      capability: "settings.manage",
      menuKey: "settings",
    },
    {
      path: "modules/catalog",
      submodule: "modules",
      page: "modules-catalog",
      labelKey: "nav.marketplace_catalog",
      section: "admin",
      order: 92,
      navGroup: "marketplace",
      navOrder: 0,
    },
    {
      path: "modules",
      submodule: "modules",
      page: "modules",
      labelKey: "nav.marketplace_installed",
      section: "admin",
      order: 92,
      navGroup: "marketplace",
      navOrder: 1,
    },
    {
      path: "modules/payment-callback",
      submodule: "modules",
      page: "modules-payment-callback",
      labelKey: "nav.marketplace_installed",
      section: "admin",
      order: 92,
      navHidden: true,
    },
    {
      path: "license",
      submodule: "modules",
      page: "license",
      labelKey: "nav.license",
      section: "admin",
      order: 93,
    },
    {
      path: "media",
      submodule: "media",
      page: "media",
      labelKey: "nav.media_library",
      section: "content",
      order: 11,
      navGroup: "media",
      navOrder: 0,
    },
    {
      path: "media/folders",
      submodule: "media",
      page: "media-folders",
      labelKey: "nav.media_folders",
      section: "content",
      order: 11,
      navGroup: "media",
      navOrder: 1,
    },
    {
      path: "media/categories",
      submodule: "media",
      page: "media-categories",
      labelKey: "nav.media_categories",
      section: "content",
      order: 11,
      navGroup: "media",
      navOrder: 2,
    },
  ],
  siteRoutes: [],
}
