import type { ModuleManifest } from "@/kernel/types"

const coreRoutes = (sub: string, labelKey: string, section = "core", order = 0) => ({
  path: sub === "dashboard" ? "" : sub,
  submodule: sub,
  labelKey,
  section,
  order,
})

export const coreManifest: ModuleManifest = {
  slug: "core",
  nameFa: "هسته",
  nameEn: "Core",
  siteTypes: ["ecommerce", "magazine", "cafe", "resume", "corporate"],
  submodules: ["auth", "setup", "tenant", "dashboard", "settings", "media", "i18n", "modules", "themes"],
  adminNav: { section: "core", order: 0 },
  adminRoutes: [
    coreRoutes("dashboard", "nav.dashboard", "overview", 0),
    {
      path: "themes",
      submodule: "themes",
      labelKey: "nav.themes",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/marketplace",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.marketplace",
      section: "admin",
      order: 90,
    },
    {
      path: "settings",
      submodule: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
    },
    {
      path: "settings/site/:section",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/:section",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/:section/:sub",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/shop/:section/:sub/:page",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.settings",
      section: "admin",
      order: 91,
      navHidden: true,
    },
    {
      path: "settings/site/security",
      submodule: "settings",
      page: "settings",
      labelKey: "nav.security",
      section: "tools",
      order: 60,
    },
    {
      path: "modules",
      submodule: "modules",
      labelKey: "nav.modules",
      section: "admin",
      order: 92,
      navHidden: true,
    },
    coreRoutes("media", "nav.media", "content", 11),
  ],
  siteRoutes: [],
}
