import type { ModuleManifest } from "@/kernel/types"

export const cmsManifest: ModuleManifest = {
  slug: "cms",
  nameFa: "محتوا",
  nameEn: "CMS",
  siteTypes: ["ecommerce", "magazine", "cafe", "resume", "corporate"],
  submodules: ["pages", "menus", "seo"],
  adminNav: { section: "content", order: 12 },
  adminRoutes: [
    {
      path: "theme-builder",
      submodule: "pages",
      page: "theme-builder",
      labelKey: "nav.theme_builder",
      section: "content",
      order: 18,
      navGroup: "theme_builder",
      navOrder: 0,
      capability: "content.manage",
    },
    {
      path: "builder/settings",
      submodule: "pages",
      page: "builder-settings",
      labelKey: "nav.builder_globals",
      section: "tools",
      order: 56,
      navGroup: "page_builder",
      navOrder: 1,
      capability: "content.manage",
    },
    {
      path: "theme-builder/:kind/:templateId",
      submodule: "pages",
      page: "builder-editor",
      labelKey: "nav.theme_builder",
      section: "content",
      order: 18,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "builder",
      submodule: "pages",
      page: "builder",
      labelKey: "nav.site_builder",
      section: "tools",
      order: 56,
      navGroup: "page_builder",
      navOrder: 0,
      capability: "content.manage",
    },
    {
      path: "builder/new",
      submodule: "pages",
      page: "builder-editor",
      labelKey: "nav.site_builder",
      section: "content",
      order: 11,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "builder/chrome/:kind",
      submodule: "pages",
      page: "builder-editor",
      labelKey: "nav.site_builder",
      section: "content",
      order: 11,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "builder/:pageId",
      submodule: "pages",
      page: "builder-editor",
      labelKey: "nav.site_builder",
      section: "content",
      order: 11,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "import/wordpress",
      submodule: "pages",
      page: "wp-import",
      labelKey: "nav.wp_import",
      section: "content",
      order: 13,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "builder/product/:productId",
      submodule: "pages",
      page: "builder-editor",
      labelKey: "nav.site_builder",
      section: "tools",
      order: 56,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "builder/post/:postId",
      submodule: "pages",
      page: "builder-editor",
      labelKey: "nav.site_builder",
      section: "tools",
      order: 56,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "builder/article/:articleId",
      submodule: "pages",
      page: "builder-editor",
      labelKey: "nav.site_builder",
      section: "tools",
      order: 56,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "pages",
      submodule: "pages",
      page: "pages",
      labelKey: "nav.cms_pages",
      section: "content",
      order: 12,
      capability: "content.manage",
    },
    {
      path: "cms",
      submodule: "pages",
      page: "pages",
      labelKey: "nav.cms_pages",
      section: "content",
      order: 12,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "pages/new",
      submodule: "pages",
      page: "page-editor",
      labelKey: "nav.cms_pages",
      section: "content",
      order: 12,
      navHidden: true,
      capability: "content.manage",
    },
    {
      path: "pages/:pageId",
      submodule: "pages",
      page: "page-editor",
      labelKey: "nav.cms_pages",
      section: "content",
      order: 12,
      navHidden: true,
      capability: "content.manage",
    },
  ],
  siteRoutes: [
    { path: "search", submodule: "pages", page: "search", labelKey: "site.pages" },
    { path: "pages/:slug", submodule: "pages", labelKey: "site.pages" },
  ],
}
